#!/bin/sh

delay=1
autodelay=3
tfile=`mktemp`

gfile(){
#tfile=`mktemp`
msize=0
mname=none
# Need to do it with tmpfile because of sh subshell stupidity
lsof -s -F nfs / | \
while read line ; do
    case $line in
		p*) pid=${line#p};;
		f*) fd=${line#f};;
		s*) size=${line#s};;
		n*) name=${line#n}
#			echo $pid $name $size / $mname $msize >&2
			if [ "${fd}" = "txt" ] ; then
				continue
			fi
			if [ "${name}" = "/" ] ; then
				continue
			fi
			if [ "${name#/usr/lib}" != "${name}" ] ; then
				continue
			fi
			if [ "${name#/lib}" != "${name}" ] ; then
				continue
			fi
			if [ $size -gt $msize ] ; then
				msize=$size
				mname=$name
			fi
			size=0
			name=undef
			echo $mname
			;;
		*) echo "Unknown $line";;
	esac
done |tail -1
}

file=$1
termcap=true
tput ho 2>/dev/null || termcap=false

if [ -z "$file" ] ; then
	file=$(gfile)
fi

if [ X"$file" = X"-a" ] ; then
	auto=$autodelay
fi

size=$(wc -c $file|awk '{print $1}')

process(){
	off=$1
	cmd=$2
	pid=$3
	fd=$4

    case $off in
		0t*) off=${off#0t};;
		0x*) off=$(echo "16i ${off#0x} p"|tr a-f A-F|dc);;
	esac

	pct=$(echo "1k $off 100 * $size / p"|dc)
	echo -n $(printf "%15s: %6s %s$el" "$cmd($pid)" "$pct%" "($off)")
	$termcap && tput ce || tput el
	echo
};

end(){
	echo
	echo
	echo -n "Abort!"
	$termcap && tput ce ve || (tput el ;tput cnorm)
	echo
	exit
}

alm(){
	nfile=$(gfile)
	if [ "${nfile}" != "${file}" ] ; then
		file=$nfile
		size=$(wc -c $file|awk '{print $1}')
		$termcap && tput cl vi || (tput clear ; tput civis)
		echo "Progress for file: ${file##*/} ($size)"
	fi
	[ ! -z "$auto" ] && (sleep $auto; kill -USR1 $pid 2>/dev/null ) &
}

trap end 2
trap alm USR1

pid=$$
[ ! -z "$auto" ] && (kill -USR1 $pid) &

$termcap && tput cl vi || (tput clear ; tput civis)
echo "Progress for file: ${file##*/} ($size)"

while : ; do
  $termcap && tput ho || tput home
  echo
  lsof -o -F co $file > $tfile 2>/dev/null
  while read line ; do
    case $line in
		c*) cmd=${line#c};;
		p*) pid=${line#p};;
		f*) fd=${line#f};;
		o*) off=${line#o}
			process "$off" "$cmd" "$pid" "$fd"
			;;
		*) echo "Unknown $line";;
	esac
  done <$tfile
  $termcap && tput cd || tput ed
  sleep $delay
done
