#!/bin/sh

file=$1
delay=1

size=$(wc -c $file|awk '{print $1}')

process(){
	off=$1
	cmd=$2
	pid=$3
	fd=$4

	pct=$(echo "1k $off 100 * $size / p"|dc)
	echo -n $(printf "%15s: %6s %s$el" "$cmd($pid)" "$pct%" "($off)")
	tput ce
	echo
};

end(){
	echo
	echo
	echo -n "Abort!"
	tput ce ve
	echo
	exit
}

trap end 2

tput cl vi
echo "Progress for file: $file ($size)"

while : ; do
  tput ho
  echo
  lsof -o -F co $file 2>/dev/null | while read line ; do
    case $line in 
		c*) cmd=${line#c};;
		p*) pid=${line#p};;
		f*) fd=${line#f};;
		o*) off=${line#o0t}
			process "$off" "$cmd" "$pid" "$fd"
			;;
		*) echo "Unknown $line";;
	esac
  done
  sleep $delay
done
