#!/bin/sh
where='/commands/custom'

while read key command ; do
	echo Set: $key
	xfconf-query -c xfce4-keyboard-shortcuts -p "$where/$key" -n -t string -s "$command"
done << EOF
<Shift>Print          xfce4-screenshooter -f
<Super>d              /home/sec/bin/dpy
<Super>r              dmenu_run -i -l 10 -fn 9x15
<Super>x              xterm -fn 9x15
Print                 true
EOF
